// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EncryptPack(arg1:string,arg2:string):Promise<string>;

export function SelectDestDialog():Promise<string>;

export function SelectPathDialog():Promise<string>;
