// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EncryptPack(arg1, arg2) {
  return window['go']['main']['App']['EncryptPack'](arg1, arg2);
}

export function SelectDestDialog() {
  return window['go']['main']['App']['SelectDestDialog']();
}

export function SelectPathDialog() {
  return window['go']['main']['App']['SelectPathDialog']();
}
